### ISSUE TITLE
安装脚本之测试情况

### ISSUE THREAD

**Issue by DemoHn** [DemoHn/obsidian-panel#16]
此issue 仅作记录用

_last update : 2016/12/9 20:00_
国外服务器 ( DigitalOcean Singapore )：

 版本 |  测试情况 
------ | -----------
Ubuntu 16.04 x64 | 
Ubuntu 16.04 x32 | __PASS__
Ubuntu 14.04.5 x64 |
Ubuntu 14.04.5 x32 |
Debian 8.6 x64 | __PASS__
Debian 8.6 x32 |
Debian 7.11 x64 |
Debian 7.11 x32 |
CentOS 7.2 x64 |
CentOS 6.8 x64 | __PASS__
CentOS 6.8 x32 | __PASS__
CentOS 5.11 x64 |
CentOS 5.11 x32 | __PASS__

国内服务器（阿里云）：
- CentOS 6.5 x64

**Comment by VonOx** [comment]
Ubuntu 16.04 x64 Install script ok
