### ISSUE TITLE
重新打开面板，控制台没有信息

### ISSUE THREAD

**Issue by mint-k** [DemoHn/obsidian-panel#22]
游戏发现错误，进入面板，发现控制台空无一物 要网页开着面板 这样才能记录控制台信息 非常不好

**Comment by DemoHn** [comment]
Duplicate of issue #14 
与issue 14 重复

**Comment by mint-k** [comment]
英语的，我看不懂

**Comment by DemoHn** [comment]
@mint-k 这个是我之前就注意到并且记录下来的问题啦=w=是我自己提的（以防自己忘了）
