### ISSUE TITLE
服务器崩溃后，控制掣按钮无效！

### ISSUE THREAD

**Issue by mint-k** [DemoHn/obsidian-panel#25]
这是个致命的问题。服务端后台报错严重，我手动按下【停止】 按钮，服务器停止了，面板仍在显示服务器正在运行，只能系统重启。这个问题很严重，我希望尽快修复。

**Comment by DemoHn** [comment]
这个问题的确很严重，很不幸的是我可能需要一段时间才能修好==因为我可能要把进程这部分代码给重写才能搞好 :cry:

**Comment by DemoHn** [comment]
refer #17
