### ISSUE TITLE
新实例，已开服，但控制台无反应，显示启动中！

### ISSUE THREAD

**Issue by mint-k** [DemoHn/obsidian-panel#29]
一直启动中，但服务器已经启动完毕，客户端已经能进去了。但面板显示启动中，控制台空白。
版本：Torch-1.9.4

**Comment by mint-k** [comment]
忘了说，重启主机 重新启动就没事了

**Comment by DemoHn** [comment]
都是同一个问题：现有的MC服务器进程监测系统不靠谱。
这个玩意并不是依照常规的方法来做的（常规的方法是用screen）而使用了事件循环。然而这玩意并没有想象中那么靠谱。
我把代码放出来有一个想法就是测试一下这个子系统的稳定性。
所以现在只能把整套系统推翻重写啦...无奈

**Comment by mint-k** [comment]
何时能更新版本？现在开始和停止功能都陆续出现这种问题。其他都能忍，这个真心麻烦啊。每次都要重启面板，面板还没有重启的功能。都有点想换回windows 用其他开服器了。

**Comment by DemoHn** [comment]
@mint-k 你把QQ号发我邮箱：demohn@foxmail.com
我加你，和你说下怎么更新版本。（现在重写得差不多了）
抱歉因为这个是公共平台，我不好随便放出我的私人信息
