### ISSUE TITLE
服务器核心无法添加

### ISSUE THREAD

**Issue by yo846tt** [DemoHn/obsidian-panel#31]
![qq 20170102202810](https://cloud.githubusercontent.com/assets/12368775/21589200/5a0ee5dc-d12a-11e6-99dd-6de138fbada6.png)
![Uploading QQ截图20170102202810.png…]()

如图，点击上传没反映！

**Comment by yo846tt** [comment]
可以了，原来没有提示啊！

**Comment by DemoHn** [comment]
@yo846tt  因为像spigot这类东西一搞就是20多M，上传需要一定时间，然后又没做进度条，于是就很长时间没有反应了。
这个页面我在新版本里已经重写了，新版本的提示就人性化了许多～

**Comment by yo846tt** [comment]
@DemoHn 期待新版，新版更新是自动更新吗？

**Comment by DemoHn** [comment]
@yo846tt 你可以手动更新它，但是自动更新。。。这玩意对于一个服务器来讲太危险了（万一哪天更新挂了不就喜闻乐见了？

**Comment by yo846tt** [comment]
@DemoHn 好吧！如果新版发布，不知在那发布呢？

**Comment by DemoHn** [comment]
@yo846tt coding.net和GitHub上都会发布。当然了，到时肯定会在MCBBS上发的
