### ISSUE TITLE
无法添加核心及下载Java

### ISSUE THREAD

**Issue by yo846tt** [DemoHn/obsidian-panel#33]
![qq 20170115210735](https://cloud.githubusercontent.com/assets/12368775/21962699/5d644802-db67-11e6-8908-6e5356632f6a.png)
如图，无法下载Java
![qq 20170115210827](https://cloud.githubusercontent.com/assets/12368775/21962704/728742b6-db67-11e6-83de-c505d6ecb0bd.png)
已经点了选择文件但是没什么反应，上传按钮也不能点。

另外，上传核心比较麻烦。不知有没有考虑过我们先通过ftp上传核心到服务器上，然后可以手动选择核心？

**Comment by DemoHn** [comment]
@yo846tt 能问下你是什么时候安装的嘛？
1. 这个是在重写代码过程中出的问题。
2. 上传选择文件没有什么反应。。是点了按钮，弹出「选择文件」窗口，然后选择jar文件之后就无法打开嘛？如果是话那应该是我文件过滤器写错掉了。（拿linux机子试的，文件的MIME可能还不大一样）
3. 没有考虑。FTP主要用处是管理「世界」里面的文件。

对了楼主应该用的是linux服务器。目前要想得到修复后的版本的话只能手动来：

```
cd /opt/obsidian-panel
git pull -f origin master
ob-panel restart
```

祝好

**Comment by yo846tt** [comment]
前天安装的。
2是点了按钮，弹出“选择文件”窗口，然后选择jar文件之后，那个上传按钮无法点
![qq 20170116085121](https://cloud.githubusercontent.com/assets/12368775/21967850/4794e2f4-dbc9-11e6-9f46-5505e48e4123.png)
如图，我已经按你说的提示修复了，但是还是不行。
不知如果我重新安装面板，还会不会出现这个问题，如果不会的话，我就重新安装吧！

**Comment by DemoHn** [comment]
@yo846tt 啊我忘了把修复的代码给push上去了。。
不过为了安全起见，我准备测试完成以后再以0.5版本的形式发布

**Comment by DemoHn** [comment]
@yo846tt 你把qq号发到demohn@foxmail.com来吧，具体有什么问题可以直接问=w=
