### ISSUE TITLE
安装后无法使用

### ISSUE THREAD

**Issue by Colinwood11** [DemoHn/obsidian-panel#36]
访问 IP：5000  连接错误   已经安装完成。试过关闭防火墙等  都无法访问是为什么

`[INFO] Copying op-panel command
[INFO] Finally, let's start!
Restart obsidian-panel...
[INFO] Start Obsidian Panel LEVEL - 2
`

**Comment by Colinwood11** [comment]
OK   不是5000端口  是80....   说明该改改了

**Comment by Colinwood11** [comment]
还有，能否支持远程MYSQL数据库？

**Comment by DemoHn** [comment]
@Colinwood11 年久失修，不好意思==
以及目前这个项目将不再在GitHub上更新，具体可以关注我们的QQ群：494903070
